AWSTemplateFormatVersion: '2010-09-09'
Description: IDC vendor database
Transform: AWS::Serverless-2016-10-31
Parameters:
  pName:
    Type: String
Resources:
  VendorTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: purchaseOrderNumber
          AttributeType: S
        - AttributeName: purchaseOrderState
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: purchaseOrderNumber
          KeyType: HASH
        - AttributeName: purchaseOrderState
          KeyType: RANGE
Outputs:
  outVendorTable:
    Value: !Ref VendorTable