AWSTemplateFormatVersion: '2010-09-09'
Description: IDL shared secrets
Transform: AWS::Serverless-2016-10-31
Parameters:
  pRefreshToken:
    Type: String
  pAppId:
    Type: String
  pClientId:
    Type: String
  pClientSecret:
    Type: String
Resources:
  RefreshToken:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /idl/refresh_token
      SecretString: !Ref pRefreshToken
  AppId:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /idl/app_id
      SecretString: !Ref pAppId
  ClientId:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /idl/client_id
      SecretString: !Ref pClientId
  ClientSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /idl/client_secret
      SecretString: !Ref pClientSecret
Outputs:
  outRefreshToken:
    Value: !Ref RefreshToken
  outAppId:
    Value: !Ref AppId
  outClientId:
    Value: !Ref ClientId
  outClientSecret:
    Value: !Ref ClientSecret